# Generated by Django 5.1.1 on 2024-09-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='phone_number',
        ),
    ]
